#!/usr/bin/env bash
# run-plugin-tests.sh — Run PHPUnit tests for a single plugin against Kanboard v1.2.47 core.
#
# Usage (from repo root):
#   ./testing/run-plugin-tests.sh <PluginName>
#
# Example:
#   ./testing/run-plugin-tests.sh ShadcnTheme
#
# Prerequisites (one-time setup):
#   1. kanboard-src must be present:
#      git clone --depth 1 --branch v1.2.47 https://github.com/kanboard/kanboard.git testing/kanboard-src
#   2. Dev dependencies must be installed:
#      composer install -d testing/kanboard-src
#   3. Plugin symlinks must exist inside testing/kanboard-src/plugins/ — they are created
#      automatically by this script on first run if missing.
#
# The script runs from the Kanboard root (testing/kanboard-src/) so all require_once paths
# and DB_FILENAME=:memory: work exactly as documented in the plugin-plans.

set -euo pipefail

PLUGIN_NAME="${1:-}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KB_SRC="${REPO_ROOT}/testing/kanboard-src"
PLUGINS_DIR="${KB_SRC}/plugins"
BOOTSTRAP="${KB_SRC}/tests/plugin-bootstrap.php"
PHPUNIT="${KB_SRC}/vendor/bin/phpunit"
CONFIG="${KB_SRC}/tests/units.sqlite.xml"

# ── Validate argument ──────────────────────────────────────────────────────────
if [[ -z "$PLUGIN_NAME" ]]; then
  echo "Usage: $0 <PluginName>"
  echo "Available plugins: BulkProjectDelete  CalendarPlugin  FeatureSync  ModMenu  ShadcnTheme  SubtaskGenerator"
  exit 1
fi

# ── Check kanboard-src is present ─────────────────────────────────────────────
if [[ ! -d "$KB_SRC" ]]; then
  echo "ERROR: testing/kanboard-src/ not found."
  echo "Run once:"
  echo "  git clone --depth 1 --branch v1.2.47 https://github.com/kanboard/kanboard.git testing/kanboard-src"
  echo "  composer install -d testing/kanboard-src"
  exit 1
fi

if [[ ! -f "$PHPUNIT" ]]; then
  echo "ERROR: vendor/bin/phpunit not found in testing/kanboard-src/."
  echo "Run: composer install -d testing/kanboard-src"
  exit 1
fi

# ── Write bootstrap (registers all plugin PSR-4 namespaces) ──────────────────
# This file lives inside the gitignored kanboard-src/ and is regenerated each run.
cat > "${BOOTSTRAP}" << 'BOOTSTRAP_EOF'
<?php
/**
 * PHPUnit bootstrap for plugin unit tests.
 * Registers all plugin namespaces with Composer's autoloader so plugin classes
 * are found without any manual require_once in individual test files.
 *
 * Auto-generated by testing/run-plugin-tests.sh — do not edit by hand.
 */
$loader = require __DIR__ . '/../vendor/autoload.php';
$pluginsDir = __DIR__ . '/../plugins';
if (is_dir($pluginsDir)) {
    foreach (new DirectoryIterator($pluginsDir) as $entry) {
        if ($entry->isDot() || !$entry->isDir()) {
            continue;
        }
        $name = $entry->getFilename();
        $loader->addPsr4("Kanboard\\Plugin\\{$name}\\", $entry->getPathname() . '/');
    }
}
BOOTSTRAP_EOF

# ── Ensure plugin symlinks exist ───────────────────────────────────────────────
for p in BulkProjectDelete CalendarPlugin FeatureSync ModMenu ShadcnTheme SubtaskGenerator; do
  if [[ ! -e "${PLUGINS_DIR}/${p}" ]]; then
    ln -s "${REPO_ROOT}/${p}" "${PLUGINS_DIR}/${p}"
    echo "Created symlink: testing/kanboard-src/plugins/${p} -> ../../${p}"
  fi
done

# ── Check the plugin exists in the repo ───────────────────────────────────────
PLUGIN_SRC="${REPO_ROOT}/${PLUGIN_NAME}"
if [[ ! -d "$PLUGIN_SRC" ]]; then
  echo "ERROR: Plugin directory not found: ${PLUGIN_SRC}"
  exit 1
fi

# ── Check the plugin has a Test/ directory ────────────────────────────────────
TEST_DIR="${PLUGINS_DIR}/${PLUGIN_NAME}/Test"
if [[ ! -d "$TEST_DIR" ]]; then
  echo "No Test/ directory found for plugin '${PLUGIN_NAME}' — nothing to run."
  echo "(Expected: ${PLUGIN_NAME}/Test/)"
  exit 0
fi

# ── Run PHPUnit from the Kanboard root ────────────────────────────────────────
echo "Running tests for plugin: ${PLUGIN_NAME}"
echo "  Kanboard root : ${KB_SRC}"
echo "  Test dir      : ${TEST_DIR}"
echo ""

cd "$KB_SRC"
exec "$PHPUNIT" \
  --bootstrap "${BOOTSTRAP}" \
  -c "${CONFIG}" \
  "plugins/${PLUGIN_NAME}/Test/" \
  --no-coverage
